services:
  mongodb:
    image: "mongo:7.0.31"
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"
    restart: "on-failure"

  datanode:
    image: "graylog/graylog-datanode:7.0.5-1"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_DATANODE_OPENSEARCH_HEAP: "3g"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:8999:8999/tcp" # DataNode API
      - "127.0.0.1:9200:9200/tcp"
      - "127.0.0.1:9300:9300/tcp"
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
    restart: "on-failure"

  graylog:
    hostname: "graylog"
    image: "graylog/graylog:7.0.5-1"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_ROOT_TIMEZONE: "America/Cuiaba"
      TZ: "America/Cuiaba"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "${GRAYLOG_HTTP_EXTERNAL_URI:-http://localhost:9000/}"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "127.0.0.1:5044:5044/tcp" # Beats
      - "0.0.0.0:1514:1514/udp" # Syslog
      - "127.0.0.1:1514:1514/tcp" # Syslog
      - "127.0.0.1:5555:5555/tcp" # RAW TCP
      - "127.0.0.1:5555:5555/udp" # RAW UDP
      - "127.0.0.1:9000:9000/tcp" # Graylog API/UI
      - "127.0.0.1:12201:12201/tcp" # GELF TCP
      - "127.0.0.1:12201:12201/udp" # GELF UDP
      - "127.0.0.1:13301:13301/tcp" # Forwarder data
      - "127.0.0.1:13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    networks:
      - default
      - observability_net
    restart: "on-failure"

volumes:
  mongodb_data:
  mongodb_config:
  graylog-datanode:
  graylog_data:
  graylog_journal:

networks:
  observability_net:
    external: true
